### ISSUE TITLE
Project Feedback: Peer Review

### ISSUE THREAD

**Issue by VigneshReddy20** [airavata-courses/terra#33]
The documenation for the project was really good and the steps mentioned to run the app locally was accurate enough to help me get things running.
The functionality to help users search through their saved work was good and is working as expected along with the data visualization feature.
Although plotting the data took some time for me but the functionality works as expected.

Thanks,
Team Viyad

**Comment by hsjoshi28** [comment]
Thank you for your feedback. Appreciate it!
